### ISSUE TITLE
the function "get_energy" seems has typo?

### ISSUE THREAD

**Issue by qiaochongzhi** [julian-urban/ising#1]
I guess that the function get_energy may contain a typo in line 29 
`np.sum(-self.b * self.spins * (np.roll(self.spins, 1, 0) + np.roll(self.spins, 1, 1)) - self.h * self.spins)`
I think it may be 
`np.sum(-self.b * self.spins * (np.roll(self.spins, 1, 0) + np.roll(self.spins, 0, 1) + np.roll(self.spins, -1, 0) + np.roll(self.spins, 0, -1) - self.h * self.spins)`

**Comment by julian-urban** [comment]
Hi, thanks for checking out my code! I wrote it a long time ago, back when I was still young and innocent, so I wouldn't be surprised if there's errors. However, I don't think this is the case here.

For starters, the signature of `np.roll` is `(array, shift, axis)`, so your `np.roll(self.spins, 0, -1)` would not give the nearest neighbor, but just the spin on the same site. Assuming you meant `np.roll(self.spins, -1, 1)` instead, this is already implemented in `get_energy_density`. This function is only used to compute Metropolis acceptance probabilities simultaneously for all sites in order to facilitate the parallelized checkerboard update. I guess it's somewhat of a misnomer since summing it over all sites would not give the same energy, the nearest neighbors being counted twice here. A better name for this function would probably be something like `get_energy_per_site` to avoid confusion. The function `get_energy` is defined without this kind of double counting, which is purely a matter of convention in our definition of the theory: we either sum over all nearest neighbors symmetrically (effectively introducing a factor of two in the hopping term by counting every link twice), or just in the positive directions (avoiding the aforementioned redundancy). Since for the energy itself we're only interested in the global value, I believe the asymmetric definition is usually preferred from a numerical point of view since it requires fewer operations. Not that it matters much in this naive python example of course :smile: 

Hope this helps! Feel free to close this issue if you agree with the above :slightly_smiling_face:

**Comment by qiaochongzhi** [comment]
Thanks a lot for your answer, your asymmetric definition is a good way to avoid counting the energy twice.
